### PR TITLE
Fix travis build

### PR DESCRIPTION
**Pull request by ahussein**
Docker based builds

### CODE REVIEW

**Comment by ahussein** [comment]
@zaibon Travis will not run your build inside a container if you have sudo:enabled in the config which is what we have. this configuration will run on a trusty virtual machine and since js does not run on that anymore, I have created that docker file. So no docker inside docker here!

**Comment by zaibon** [comment]
ok I didn't know that. But still, I have all my test for the 0-robot running on travis and I don't need to install docker and do all this cruft to get jumpscale working. So there is something wrong in how you do things here. Check 0-robot repo to see how I made it works there: https://github.com/threefoldtech/0-robot/tree/development_simple

**Comment by ahussein** [comment]
I already checked that before...the problem there that it doesn't install JS the official way ...I want the Travis installation to follow the steps in the repo and use the install script

**Comment by zaibon** [comment]
I see. Very sad but I guess there is no other way then...

**Comment by zaibon** [comment]
@ahussein BTW, I though jumpscale doesn't requires to run as root anymore on the development_simple branch. So maybe you can get rid of the `sudo: true` ?

**Pull request merged**
